In [1]:
import pandas as pd

In [2]:
pd.options.display.max_columns = 88

In [3]:
df = pd.read_csv("https://storage.googleapis.com/datamexico-data/inegi_intercensal_census/TR_PERSONA32.CSV", 
                 encoding="latin-1",
                 dtype=str,
                 low_memory=False)

In [4]:
df_labels = pd.ExcelFile("https://docs.google.com/spreadsheets/d/e/2PACX-1vR08Js9Sh4nNTMe5uBcsDUFedG5MOjIf90p6EHAr1_sWY5kpnI3xUvyPHzQpTEUrXz1pskaoc0uyea6/pub?output=xlsx")

In [5]:
df.columns = df.columns.str.lower()

In [6]:
# Adding IDs columns and renaming factor as population
df["loc_id"] = df["ent"] + df["mun"] + df["loc50k"]

In [7]:
df["mun_id_trab"] = df["ent_pais_trab"] + df["mun_trab"]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 462568 entries, 0 to 462567
Data columns (total 88 columns):
id_viv                462568 non-null object
id_persona            462568 non-null object
ent                   462568 non-null object
nom_ent               462568 non-null object
mun                   462568 non-null object
nom_mun               462568 non-null object
loc50k                462568 non-null object
nom_loc               462568 non-null object
cobertura             462568 non-null object
estrato               462568 non-null object
upm                   462568 non-null object
factor                462568 non-null object
numper                462568 non-null object
sexo                  462568 non-null object
edad                  462568 non-null object
parent                462568 non-null object
parent_otro_c         462568 non-null object
ident_madre           462568 non-null object
ident_padre           462568 non-null object
sersalud              462568 non-n

In [9]:
df["mun_id_trab"].unique()

array([nan, '032001', '032023', '032019', '999999', '032044', '032048',
       '032020', '032999', '032056', '032042', '014999', '032005',
       '032033', '014120', '032030', '032055', '032045', '030193',
       '001001', '014039', '032002', '014060', '014091', '014116',
       '032034', '014118', '019039', '014050', '032010', '014008',
       '014024', '014064', '032038', '032054', '025017', '032012',
       '014109', '014035', '014078', '032051', '032003', '014104',
       '014115', '032031', '032004', '014076', '032047', '018999',
       '014019', '032026', '032058', '032032', '032013', '015088',
       '001999', '010005', '009999', '032017', '032007', '005025',
       '032028', '022014', '032025', '001002', '030039', '032036',
       '021114', '015999', '026999', '006007', '032037', '032049',
       '020067', '010007', '032050', '011017', '005999', '024028',
       '032053', '014031', '011007', '032039', '010001', '026036',
       '018017', '008019', '005035', '032024', '011037', 

In [10]:
df["ent_pais_trab"].unique()

array([nan, '032', '998', '999', '014', '030', '001', '019', '025', '221',
       '018', '015', '010', '009', '005', '022', '021', '026', '006',
       '020', '011', '024', '008', '028', '012', '017', '013', '213',
       '002', '007', '016', '446', '004', '023', '027', '003', '225',
       '239'], dtype=object)

In [11]:
df["mun_trab"].unique()

array([nan, '001', '023', '019', '999', '044', '048', '020', '056', '042',
       '005', '033', '120', '030', '055', '045', '193', '039', '002',
       '060', '091', '116', '034', '118', '050', '010', '008', '024',
       '064', '038', '054', '017', '012', '109', '035', '078', '051',
       '003', '104', '115', '031', '004', '076', '047', '026', '058',
       '032', '013', '088', '007', '025', '028', '014', '036', '114',
       '037', '049', '067', '053', '021', '006', '018', '040', '016',
       '098', '022', '027', '041', '011', '015', '009', '052', '066',
       '029', '071', '046', '057', '101', '043', '133', '108', '073',
       '061', '069', '208', '075', '097', '106', '131', '083', '059',
       '080'], dtype=object)

In [12]:
df.head()

id_viv      id_persona ent    nom_ent  mun nom_mun loc50k  \
0  320010000001  32001000000102  32  Zacatecas  001  Apozol   0000   
1  320010000001  32001000000101  32  Zacatecas  001  Apozol   0000   
2  320010000002  32001000000207  32  Zacatecas  001  Apozol   0000   
3  320010000002  32001000000205  32  Zacatecas  001  Apozol   0000   
4  320010000002  32001000000203  32  Zacatecas  001  Apozol   0000   

                                   nom_loc cobertura    estrato     upm  \
0  Localidad de menos de 50 mil habitantes         2  32-001-04  284040   
1  Localidad de menos de 50 mil habitantes         2  32-001-04  284040   
2  Localidad de menos de 50 mil habitantes         2  32-001-04  284052   
3  Localidad de menos de 50 mil habitantes         2  32-001-04  284052   
4  Localidad de menos de 50 mil habitantes         2  32-001-04  284052   

  factor numper sexo edad parent parent_otro_c ident_madre ident_padre  \
0      1      2    3   58      2           201          97          97   
1      1      1    1   62      1           101          96          96   
2      1      7    1    2      3           301           2           1   
3      1      5    1   10      3           301           2           1   
4      1      3    3   17      3           301           2           1   

  sersalud afrodes acta_nac dhsersal1 dhsersal2 perte_indigena ent_pais_nac  \
0        5       3        1         8       NaN              3          032   
1        1       3        1         8       NaN              3          032   
2        6       3        1         8       NaN              1          032   
3        6       3        1         8       NaN              1          032   
4        6       3        1         8       NaN              1          032   

  nacionalidad hlengua qdialect_c qdialect_inali hespanol elengua asisten  \
0            5       3        NaN            NaN      NaN       3       7   
1            5       3        NaN            NaN      NaN       3       7   
2            5     NaN        NaN            NaN      NaN     NaN     NaN   
3            5       3        NaN            NaN      NaN       3       5   
4            5       3        NaN            NaN      NaN       3       5   

  mun_asi nom_mun_asi ent_pais_asi tie_traslado_escu med_traslado_esc1  \
0     NaN         NaN          NaN               NaN               NaN   
1     NaN         NaN          NaN               NaN               NaN   
2     NaN         NaN          NaN               NaN               NaN   
3     001      Apozol          032                 1                 6   
4     001      Apozol          032                 1                 6   

  med_traslado_esc2 med_traslado_esc3 escolari nivacad alfabet escoacum  \
0               NaN               NaN        1       2       7        1   
1               NaN               NaN        6       2       5        6   
2               NaN               NaN      NaN     NaN     NaN      NaN   
3               NaN               NaN        4       2       5        4   
4               NaN               NaN        1       4       5       10   

  mun_res10 nom_mun_res10 ent_pais_res10 situa_conyugal ident_pareja conact  \
0       001        Apozol            032              5            1     35   
1       001        Apozol            032              5            2     35   
2       NaN           NaN            NaN            NaN          NaN    NaN   
3       001        Apozol            032            NaN          NaN    NaN   
4       001        Apozol            032              6          NaN     31   

  ocupacion_c situacion_trab aguinaldo vacaciones servicio_medico utilidades  \
0         NaN            NaN       NaN        NaN             NaN        NaN   
1         NaN            NaN       NaN        NaN             NaN        NaN   
2         NaN            NaN       NaN        NaN             NaN        NaN   
3         NaN            NaN       NaN        NaN             N

In [13]:
df[df["tie_traslado_trab"].isnull()]

id_viv      id_persona ent    nom_ent  mun  \
0       320010000001  32001000000102  32  Zacatecas  001   
1       320010000001  32001000000101  32  Zacatecas  001   
2       320010000002  32001000000207  32  Zacatecas  001   
3       320010000002  32001000000205  32  Zacatecas  001   
4       320010000002  32001000000203  32  Zacatecas  001   
5       320010000002  32001000000204  32  Zacatecas  001   
6       320010000002  32001000000206  32  Zacatecas  001   
7       320010000002  32001000000202  32  Zacatecas  001   
8       320010000002  32001000000201  32  Zacatecas  001   
9       320010000003  32001000000303  32  Zacatecas  001   
10      320010000003  32001000000304  32  Zacatecas  001   
11      320010000003  32001000000302  32  Zacatecas  001   
13      320010000004  32001000000402  32  Zacatecas  001   
14      320010000004  32001000000401  32  Zacatecas  001   
15      320010000004  32001000000403  32  Zacatecas  001   
16      320010000005  32001000000504  32  Zacatecas  001   
17      320010000005  32001000000505  32  Zacatecas  001   
18      320010000005  32001000000502  32  Zacatecas  001   
19      320010000005  32001000000501  32  Zacatecas  001   
20      320010000005  32001000000503  32  Zacatecas  001   
21      320010000006  32001000000601  32  Zacatecas  001   
24      320010000008  32001000000803  32  Zacatecas  001   
25      320010000008  32001000000802  32  Zacatecas  001   
31      320010000010  32001000001002  32  Zacatecas  001   
33      320010000011  32001000001103  32  Zacatecas  001   
34      320010000011  32001000001104  32  Zacatecas  001   
35      320010000011  32001000001102  32  Zacatecas  001   
37      320010000012  32001000001205  32  Zacatecas  001   
38      320010000012  32001000001202  32  Zacatecas  001   
42      320010000013  32001000001301  32  Zacatecas  001   
...              ...             ...  ..        ...  ...   
462530  320580000644  32058000064403  32  Zacatecas  058   
462531  320580000644  32058000064404  32  Zacatecas  058   
462533  320580000645  32058000064501  32  Zacatecas  058   
462535  320580000646  32058000064604  32  Zacatecas  058   
462536  320580000646  32058000064602  32  Zacatecas  058   
462537  320580000646  32058000064603  32  Zacatecas  058   
462538  320580000646  32058000064601  32  Zacatecas  058   
462539  320580000646  32058000064605  32  Zacatecas  058   
462540  320580000646  32058000064606  32  Zacatecas  058   
462541  320580000647  32058000064702  32  Zacatecas  058   
462542  320580000647  32058000064701  32  Zacatecas  058   
462543  320580000648  32058000064804  32  Zacatecas  058   
462544  320580000648  32058000064803  32  Zacatecas  058   
462545  320580000648  32058000064802  32  Zacatecas  058   
462547  320580000649  32058000064902  32  Zacatecas  058   
462548  320580000649  32058000064903  32  Zacatecas  058   
462549  320580000649  32058000064904  32  Zacatecas  058   
462551  320580000650  32058000065003  32  Zacatecas  058   
462552  320580000650  32058000065004  32  Zacatecas  058   
462555  320580000651  32058000065103  32  Zacatecas  058   
462556  320580000651  32058000065102  32  Zacatecas  058   
462558  320580000652  32058000065201  32  Zacatecas  058   
462559  320580000652  32058000065202  32  Zacatecas  058   
462560  320580000653  32058000065302  32  Zacatecas  058   
462561  320580000653  32058000065301  32  Zacatecas  058   
462563  320580000655  32058000065502  32  Zacatecas  058   
462564  320580000655  32058000065501  32  Zacatecas  058   
462565  320580000655  32058000065503  32  Zacatecas  058   
462566  320580000655  32058000065505  32  Zacatecas  058   
462567  320580000655  32058000065504  32  Zacatecas  058   

                      nom_mun loc50k                                  nom_loc  \
0                      Apozol   0000  Localidad de menos de 50 mil habitantes   
1                      Apozol   0000  Localidad de menos de 50 mil habitantes   
2                      Apozol   0000  Localidad de

In [14]:
pivote = df["tie_traslado_trab"].isnull()

In [15]:
pivote.unique()

array([ True, False])

In [16]:
pivote2 = df["tie_traslado_trab"].isnull()

In [17]:
pivote2.unique()

array([ True, False])

In [18]:
# Transforming certains str columns into int values
df["loc_id"] = df["loc_id"].astype(int)
df["factor"] = df["factor"].astype(int)
#df["tie_traslado_trab"] = df["tie_traslado_trab"].astype(int)
#df["med_traslado_trab1"] = df["med_traslado_trab1"].astype(int)

In [19]:
df["factor"].sum()

1579209

In [20]:
df.fillna('99999', inplace=True)

In [21]:
# List of columns for the next df
params            = ["sexo", "parent", "sersalud", "dhsersal1", "nacionalidad", "conact", "tie_traslado_trab", "med_traslado_trab1"]
params_translated = ["sex", "parent", "sersalud", "dhsersal1", "nationality", "laboral_condition", "time_to_work", "transport_mean_work"]

In [22]:
# For cycle in order to change the content of a column from previous id, into the new ones (working for translate too)
for sheet in params:
    df_l = pd.read_excel(df_labels, sheet)
    df[sheet] = df[sheet].astype(int)
    df[sheet] = df[sheet].replace(dict(zip(df_l.prev_id, df_l.name_en)))

In [23]:
# Condense df around params list, mun_id and loc_id, and sum over population (factor)
df = df.groupby(params+ ["loc_id"]).sum().reset_index(col_fill="ffill")

In [24]:
# Renaming of certains columns
df.rename(index=str, columns={"factor": "population",
                              "nacionalidad": "nationality",
                              "sexo": "sex",
                              "conact": "laboral_condition",
                              "tie_traslado_trab": "time_to_work",
                              "med_traslado_trab1": "transport_mean_work"}, inplace=True)

In [27]:
df

sex                       parent sersalud  \
0     Female  Another Family Relationship   ISSSTE   
1     Female  Another Family Relationship   ISSSTE   
2     Female  Another Family Relationship   ISSSTE   
3     Female  Another Family Relationship   ISSSTE   
4     Female  Another Family Relationship   ISSSTE   
5     Female  Another Family Relationship   ISSSTE   
6     Female  Another Family Relationship   ISSSTE   
7     Female  Another Family Relationship   ISSSTE   
8     Female  Another Family Relationship   ISSSTE   
9     Female  Another Family Relationship   ISSSTE   
10    Female  Another Family Relationship   ISSSTE   
11    Female  Another Family Relationship   ISSSTE   
12    Female  Another Family Relationship   ISSSTE   
13    Female  Another Family Relationship   ISSSTE   
14    Female  Another Family Relationship   ISSSTE   
15    Female  Another Family Relationship   ISSSTE   
16    Female  Another Family Relationship   ISSSTE   
17    Female  Another Family Relationship   ISSSTE   
18    Female  Another Family Relationship   ISSSTE   
19    Female  Another Family Relationship   ISSSTE   
20    Female  Another Family Relationship   ISSSTE   
21    Female  Another Family Relationship   ISSSTE   
22    Female  Another Family Relationship   ISSSTE   
23    Female  Another Family Relationship   ISSSTE   
24    Female  Another Family Relationship   ISSSTE   
25    Female  Another Family Relationship   ISSSTE   
26    Female  Another Family Relationship   ISSSTE   
27    Female  Another Family Relationship   ISSSTE   
28    Female  Another Family Relationship   ISSSTE   
29    Female  Another Family Relationship   ISSSTE   
...      ...                          ...      ...   
5186    Male            Spouse or Partner   ISSSTE   
5187    Male            Spouse or Partner   ISSSTE   
5188    Male            Spouse or Partner   ISSSTE   
5189    Male            Spouse or Partner   ISSSTE   
5190    Male            Spouse or Partner   ISSSTE   
5191    Male            Spouse or Partner   ISSSTE   
5192    Male            Spouse or Partner   ISSSTE   
5193    Male            Spouse or Partner   ISSSTE   
5194    Male            Spouse or Partner   ISSSTE   
5195    Male            Spouse or Partner   ISSSTE   
5196    Male            Spouse or Partner   ISSSTE   
5197    Male            Spouse or Partner   ISSSTE   
5198    Male            Spouse or Partner   ISSSTE   
5199    Male            Spouse or Partner   ISSSTE   
5200    Male            Spouse or Partner   ISSSTE   
5201    Male            Spouse or Partner   ISSSTE   
5202    Male            Spouse or Partner   ISSSTE   
5203    Male            Spouse or Partner   ISSSTE   
5204    Male            Spouse or Partner   ISSSTE   
5205    Male            Spouse or Partner   ISSSTE   
5206    Male            Spouse or Partner   ISSSTE   
5207    Male            Spouse or Partner   ISSSTE   
5208    Male            Spouse or Partner   ISSSTE   
5209    Male            Spouse or Partner   ISSSTE   
5210    Male            Spouse or Partner   ISSSTE   
5211    Male            Spouse or Partner   ISSSTE   
5212    Male            Spouse or Partner   ISSSTE   
5213    Male            Spouse or Partner   ISSSTE   
5214    Male            Spouse or Partner   ISSSTE   
5215    Male            Spouse or Partner   ISSSTE   

                                              dhsersal1   nationality  \
0                                IMSS (Social Security)           Yes   
1                                IMSS (Social Security)           Yes   
2                                IMSS (Social Security)           Yes   
3                                IMSS (Social Security)           Yes   
4                                IMSS (Social Security)           Yes   
5                                IMSS (Social Security)           Yes   
6                                IMSS (Social Security)           Yes   
7                                                ISSSTE            No   
8  

In [25]:
# Condense df around params list, mun_id and loc_id, and sum over population (factor)
# df = df.groupby(params_translated + ["loc_id"]).sum().reset_index(col_fill="ffill")

In [26]:
for col in ["sex", "parent", "sersalud", "dhsersal1", "nationality", "time_to_work", "transport_mean_work"]:
            df[col] = df[col].astype(int)

ValueError: invalid literal for int() with base 10: 'Female'

In [ ]:
df

In [ ]:
#df[df['time_to_work'].isnull()]

In [ ]:
df.sum()

In [ ]:
df.replace(99999, pd.np.nan, inplace=True)

In [ ]:
for ele in df.time_to_work.unique():
    try:
        df.time_to_work = df.time_to_work.replace(ele, int(ele))
    except:
        continue

In [ ]:
df.time_to_work

In [ ]:
df["time_to_work"] = df["time_to_work"].astype(pd.Int8Dtype())

In [ ]:
pd.__version__