In [29]:
import pandas as pd
from simpledbf import Dbf5

In [30]:
pd.options.display.max_columns = 96

In [31]:
# Loading new columns labels (2010) to the file
path_labels = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQrgV5L1KtlO35d4-j2uUEHifL_S2NNmqM9dU6SuMCbHfS_tYQxaTwJJmOaFz-k9kemwIlfN9i381lt/pub?output=xlsx"
df_labels = pd.ExcelFile(path_labels)

In [32]:
dbf = Dbf5("Personas_01.dbf", codec="latin-1")
df = dbf.to_dataframe()

In [33]:
df.columns = df.columns.str.lower()

In [34]:
df.head()

ent         nom_ent  mun         nom_mun loc50k  \
0  01  Aguascalientes  001  Aguascalientes   0000   
1  01  Aguascalientes  001  Aguascalientes   0000   
2  01  Aguascalientes  001  Aguascalientes   0000   
3  01  Aguascalientes  001  Aguascalientes   0000   
4  01  Aguascalientes  001  Aguascalientes   0000   

                                   nom_loc    id_viv     id_per clavivp  \
0  Localidad de menos de 50 mil habitantes  00068033  000284687       1   
1  Localidad de menos de 50 mil habitantes  00068033  000284692       1   
2  Localidad de menos de 50 mil habitantes  00068033  000284695       1   
3  Localidad de menos de 50 mil habitantes  00068039  000284701       1   
4  Localidad de menos de 50 mil habitantes  00068039  000284707       1   

  numper sexo edad parent otropare_c idmadre idmadrec idpadre idpadrec  \
0  00001    1  064     01        NaN     NaN       88     NaN       88   
1  00002    3  046     02        NaN     NaN       88     NaN       88   
2  00003    3  020     03        303      02      NaN     NaN       88   
3  00001    3  084     01        NaN     NaN       88     NaN       88   
4  00002    1  047     03        NaN      01      NaN     NaN       88   

  lnacedo_c lnacpais_c sersalud dhsersal1 dhsersal2 otrarel_c discap1 discap2  \
0       001        NaN       05         5       NaN    110300     NaN     NaN   
1       001        NaN       01         1       NaN    110300     NaN     NaN   
2       011        NaN       01         1       NaN    110300     NaN     NaN   
3       014        NaN       07         2       NaN    150300     NaN     NaN   
4       001        NaN       05         8       NaN    110300      10      11   

  discap3 discap4 discap5 discap6 discap7 discap8 causadis1 causadis2  \
0     NaN     NaN     NaN     NaN     NaN      17       NaN       NaN   
1     NaN     NaN     NaN     NaN     NaN      17       NaN       NaN   
2     NaN     NaN     NaN     NaN     NaN      17       NaN       NaN   
3     NaN     NaN     NaN     NaN     NaN      17       NaN       NaN   
4     NaN     NaN     NaN     NaN      16     NaN         3         3   

  causadis3 causadis4 causadis5 causadis6 causadis7 hlengua qdialect_c  \
0       NaN       NaN       NaN       NaN       NaN       3        NaN   
1       NaN       NaN       NaN       NaN       NaN       3        NaN   
2       NaN       NaN       NaN       NaN       NaN       3        NaN   
3       NaN       NaN       NaN       NaN       NaN       3        NaN   
4       NaN       NaN       NaN       NaN         3       3        NaN   

  hespanol clengua li_inali peretn asisten escolari nivacad antesc nomcar_c  \
0      NaN       3      NaN      3       3       06      02    NaN      NaN   
1      NaN       3      NaN      3       3       06      02    NaN      NaN   
2      NaN       3      NaN      3       1       01      08      3      513   
3      NaN       3      NaN      3       3       03      02    NaN      NaN   
4      NaN       3      NaN      3       3       06      02    NaN      NaN   

  escoacum niv_car alfabet res05edo_c res05pai_c mun05otr_c       nom_mun05  \
0       06     NaN       1        NaN        221        NaN             NaN   
1       06     NaN       1        019        NaN        026       Guadalupe   
2       13    4513       1        019        NaN        026       Guadalupe   
3       03     NaN       1        001        NaN        001  Aguascalientes   
4       06     NaN       1        001        NaN        001  Aguascalientes   

  estcon idconyuge idconyugec conact ocuactiv_c sittra preslab1 preslab2  \
0      1        02        NaN     14       6116      5      NaN      NaN   
1      1        01        NaN     60        NaN    NaN      NaN      NaN   
2      8       NaN        NaN     50        NaN    NaN      NaN      NaN   
3      4       NaN        NaN     99        NaN    NaN      NaN      NaN   
4      8       NaN        NaN     70        NaN    NaN      NaN      NaN   

  preslab

In [35]:
# Adding IDs columns and renaming factor as population
df["loc_id"] = df["ent"] + df["mun"] + df["loc50k"]
df["mun_id_trab"] = df["ltrabpai_c"] + df["ltrabmun_c"]
df["year"] = 2010
df["edad"] = df["edad"].astype(int)

In [36]:
df["factor"].sum()

1178800

In [37]:
#df["mun_id_trab"] = df["ltrabpai_c"] + df["ltrabmun_c"]

#df["mun_id_trab"].replace(pd.np.nan , 0, inplace=True)
df["mun_id_trab"].fillna("0", inplace=True)
df["mun_id_trab"] = df["mun_id_trab"].astype(int)
df["edad"] = df["edad"].astype(object)

In [38]:
df.loc[df["mun_id_trab"] > 33000, "mun_id_trab"] = 0
df["mun_id_trab"].replace(pd.np.nan , 0, inplace=True)

In [39]:
df["nivacad"].fillna("1000", inplace=True)

In [40]:
len(df["mun_id_trab"].unique())

95

In [41]:
df.groupby(["ltrabpai_c", "ltrabmun_c", "mun_id_trab"]).sum()

factor      year
ltrabpai_c ltrabmun_c mun_id_trab                  
001        001        1001         321412  22670790
           002        1002           9390   2200950
           003        1003          18375   3137610
           004        1004           3154   2003970
           005        1005          27308   2679330
           006        1006          10051   2327580
           007        1007          13734   2932590
           008        1008           1991   1811010
           009        1009           3871   1089420
           010        1010           3349   1513530
           011        1011          11769   2729580
           999        1999           7803   1620060
002        004        2004             33      2010
004        002        4002             18      2010
           009        4009             41      4020
005        035        5035             12      4020
           999        5999             27      4020
008        999        8999              4      2010
009        003        9003             49      4020
           010        9010             12      4020
           015        9015              8      2010
           999        9999           1219     88440
010        999        10999             8      2010
011        007        11007            15      4020
           015        11015           243     18090
           017        11017            23      6030
           020        11020           262     26130
           999        11999           178     24120
012        999        12999            29      2010
013        048        13048            12      2010
...                                   ...       ...
024        028        24028           519     42210
           999        24999            31     10050
026        003        26003             8      2010
           999        26999             4      2010
027        004        27004            37      2010
028        035        28035             8      2010
029        033        29033            20      2010
030        072        30072             2      2010
           193        30193            76      4020
           999        30999            12      2010
032        007        32007            25      6030
           008        32008            39     10050
           010        32010            18      6030
           014        32014             5      2010
           016        32016            14      2010
           017        32017            29      4020
           019        32019            52     10050
           020        32020            11      4020
           023        32023            23      4020
           024        32024           885    166830
           025        32025           206     44220
           026        32026            12      6030
           036        32036            70     28140
           044        32044            25      2010
           052        32052            64     12060
           053        32053             4      2010
           054        32054             9      2010
           056        32056          1048    148740
           057        32057             2      2010
           999        32999           833    211050

[94 rows x 2 columns]

In [42]:
df.mun_id_trab.unique()

array([ 1001,     0, 32056,  1011, 14999, 14116,  9999, 14039,  1003,
        1010, 14035,  1006, 15104,  5999, 32999, 11015,  1005,  1002,
       24028,  4002,  1007, 30193, 15999, 32007, 32020, 14064, 11020,
       14073, 32010,  1009, 32016, 32052,  9003, 12999, 22014, 32024,
       14080, 11999, 32023, 15106, 14006, 17007, 15057, 14008, 21999,
       30999, 14046, 19999, 14053, 32053,  1004, 21114, 27004,  1999,
       14091, 22999, 14098, 16999,  2004, 19039, 14057,  4009, 32036,
       14109,  5035, 26999, 23999, 10999, 32054, 11017, 24999, 26003,
       32019, 18999, 11007, 32025, 32057, 32008, 32026, 32017,  1008,
       32044, 29033, 14093, 15060, 23005, 20067,  9015, 13048, 28035,
       14124,  9010, 30072, 32014,  8999], dtype=int64)

In [43]:
df["laboral_condition"] = ""
df["time_to_work"] = ""
df["transport_mean_work"] = ""
df["time_to_ed_facilities"] = ""
df["transport_mean_ed_facilities"] = ""

In [44]:
params_nan = ["laboral_condition", "time_to_work", "transport_mean_work", "time_to_ed_facilities", "transport_mean_ed_facilities"]


In [45]:
# Transforming certains str columns into int values
df["loc_id"] = df["loc_id"].astype(int)
df["factor"] = df["factor"].astype(int)

In [46]:
df.head()

ent         nom_ent  mun         nom_mun loc50k  \
0  01  Aguascalientes  001  Aguascalientes   0000   
1  01  Aguascalientes  001  Aguascalientes   0000   
2  01  Aguascalientes  001  Aguascalientes   0000   
3  01  Aguascalientes  001  Aguascalientes   0000   
4  01  Aguascalientes  001  Aguascalientes   0000   

                                   nom_loc    id_viv     id_per clavivp  \
0  Localidad de menos de 50 mil habitantes  00068033  000284687       1   
1  Localidad de menos de 50 mil habitantes  00068033  000284692       1   
2  Localidad de menos de 50 mil habitantes  00068033  000284695       1   
3  Localidad de menos de 50 mil habitantes  00068039  000284701       1   
4  Localidad de menos de 50 mil habitantes  00068039  000284707       1   

  numper sexo edad parent otropare_c idmadre idmadrec idpadre idpadrec  \
0  00001    1   64     01        NaN     NaN       88     NaN       88   
1  00002    3   46     02        NaN     NaN       88     NaN       88   
2  00003    3   20     03        303      02      NaN     NaN       88   
3  00001    3   84     01        NaN     NaN       88     NaN       88   
4  00002    1   47     03        NaN      01      NaN     NaN       88   

  lnacedo_c lnacpais_c sersalud dhsersal1 dhsersal2 otrarel_c discap1 discap2  \
0       001        NaN       05         5       NaN    110300     NaN     NaN   
1       001        NaN       01         1       NaN    110300     NaN     NaN   
2       011        NaN       01         1       NaN    110300     NaN     NaN   
3       014        NaN       07         2       NaN    150300     NaN     NaN   
4       001        NaN       05         8       NaN    110300      10      11   

  discap3 discap4 discap5 discap6 discap7 discap8 causadis1 causadis2  \
0     NaN     NaN     NaN     NaN     NaN      17       NaN       NaN   
1     NaN     NaN     NaN     NaN     NaN      17       NaN       NaN   
2     NaN     NaN     NaN     NaN     NaN      17       NaN       NaN   
3     NaN     NaN     NaN     NaN     NaN      17       NaN       NaN   
4     NaN     NaN     NaN     NaN      16     NaN         3         3   

  causadis3 causadis4 causadis5 causadis6 causadis7 hlengua qdialect_c  \
0       NaN       NaN       NaN       NaN       NaN       3        NaN   
1       NaN       NaN       NaN       NaN       NaN       3        NaN   
2       NaN       NaN       NaN       NaN       NaN       3        NaN   
3       NaN       NaN       NaN       NaN       NaN       3        NaN   
4       NaN       NaN       NaN       NaN         3       3        NaN   

  hespanol clengua li_inali peretn asisten escolari nivacad  \
0      NaN       3      NaN      3       3       06      02   
1      NaN       3      NaN      3       3       06      02   
2      NaN       3      NaN      3       1       01      08   
3      NaN       3      NaN      3       3       03      02   
4      NaN       3      NaN      3       3       06      02   

               ...              mun05otr_c       nom_mun05 estcon idconyuge  \
0              ...                     NaN             NaN      1        02   
1              ...                     026       Guadalupe      1        01   
2              ...                     026       Guadalupe      8       NaN   
3              ...                     001  Aguascalientes      4       NaN   
4              ...                     001  Aguascalientes      8       NaN   

  idconyugec conact ocuactiv_c sittra preslab1 preslab2 preslab3 preslab4  \
0        NaN     14       6116      5      NaN      NaN      NaN      NaN   
1        NaN     60        NaN    NaN      NaN      NaN      NaN      NaN   
2        NaN     50        NaN    NaN      NaN      NaN      NaN      NaN   
3        NaN     99        NaN    NaN      NaN      NaN      NaN      NaN   
4        NaN     70        NaN    NaN      NaN      NaN      NaN      NaN   

  preslab5 preslab6 hortra ingtrmen acttrab_c ltrabpai_c ltrabmun_c  \
0      NaN      NaN    020  

In [50]:
params = ["sexo", "parent", "sersalud", "dhsersal1", "nivacad"]
params_nan = ["laboral_condition", "time_to_work", "transport_mean_work", "time_to_ed_facilities", "transport_mean_ed_facilities"]
params_int = ["loc_id", "year", "mun_id_trab"]

In [51]:
# For cycle in order to change the content of a column from previous id, into the new ones (working for translate too)
for sheet in params:
    df_l = pd.read_excel(df_labels, sheet)
    df[sheet] = df[sheet].astype(int)
    df[sheet] = df[sheet].replace(dict(zip(df_l.prev_id, df_l.id)))

In [52]:
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQrgV5L1KtlO35d4-j2uUEHifL_S2NNmqM9dU6SuMCbHfS_tYQxaTwJJmOaFz-k9kemwIlfN9i381lt/pub?output=xlsx"
pivote = pd.read_excel(url, sheet_name="tramo_edad", encoding="latin-1", dtype={"interval_upper": "int64", "interval_lower": "int64"})
for años in df.edad.unique():
    for level in range(pivote.shape[0]):
        if (años >= pivote.interval_lower[level]) & (años < pivote.interval_upper[level]):
            df.edad.replace(años, str(pivote.id[level]), inplace=True)
            break

df.edad = df.edad.astype("int")

In [53]:
df.mun_id_trab.unique()

array([ 1001,     0, 32056,  1011, 14999, 14116,  9999, 14039,  1003,
        1010, 14035,  1006, 15104,  5999, 32999, 11015,  1005,  1002,
       24028,  4002,  1007, 30193, 15999, 32007, 32020, 14064, 11020,
       14073, 32010,  1009, 32016, 32052,  9003, 12999, 22014, 32024,
       14080, 11999, 32023, 15106, 14006, 17007, 15057, 14008, 21999,
       30999, 14046, 19999, 14053, 32053,  1004, 21114, 27004,  1999,
       14091, 22999, 14098, 16999,  2004, 19039, 14057,  4009, 32036,
       14109,  5035, 26999, 23999, 10999, 32054, 11017, 24999, 26003,
       32019, 18999, 11007, 32025, 32057, 32008, 32026, 32017,  1008,
       32044, 29033, 14093, 15060, 23005, 20067,  9015, 13048, 28035,
       14124,  9010, 30072, 32014,  8999], dtype=int64)

In [54]:
df = df.groupby(params + params_nan + params_int + ["edad"]).sum().reset_index(col_fill="ffill")

In [55]:
# Renaming of certains columns
df.rename(index=str, columns={"factor": "population",
                              "edad": "age",
                              "sexo": "sex",
                              "nivacad": "academic_degree"}, inplace=True)

In [56]:
df.mun_id_trab.unique()

array([    0,  1001,  1005,  1002,  1003,  1004,  1006,  1007,  1009,
        1011,  1010,  1999, 32007, 14116, 14999, 15999, 32056, 32999,
       14046, 32024, 32036, 14053,  1008,  9999, 11020, 14035, 19039,
       19999, 22999, 30999, 22014, 24028, 14098, 15106, 28035,  9010,
       14039, 14109, 32025,  5999,  4002,  4009, 11015, 11999, 21999,
       26003, 15060, 14093, 14057, 14064, 32008, 32052, 11017, 30072,
       32054, 32020, 32010, 14073, 24999, 18999, 32023, 32016, 30193,
       15057, 26999,  5035,  9003, 14006, 29033, 16999, 32019, 23999,
       15104, 11007, 27004, 32017, 14124, 17007,  8999, 10999, 32014,
       13048, 32026, 32044,  9015, 20067, 14008, 21114, 14091, 32057,
        2004, 12999, 32053, 23005, 14080], dtype=int64)

In [57]:
df.head()

sex  parent  sersalud  dhsersal1  academic_degree laboral_condition  \
0    1       1         1          1                0                     
1    1       1         1          1                0                     
2    1       1         1          1                0                     
3    1       1         1          1                0                     
4    1       1         1          1                0                     

  time_to_work transport_mean_work time_to_ed_facilities  \
0                                                          
1                                                          
2                                                          
3                                                          
4                                                          

  transport_mean_ed_facilities    loc_id  year  mun_id_trab  age  population  
0                               10010000  2010            0    2          30  
1                               10010000  2010            0    3          56  
2                               10010000  2010            0    4         102  
3                               10010000  2010         1001    2          90  
4                               10010000  2010         1001    3         281

In [58]:
df["time_to_work"].replace(0, pd.np.nan, inplace=True)
df["transport_mean_work"].replace(0, pd.np.nan, inplace=True)
df["academic_degree"].replace(1000, pd.np.nan, inplace=True)
df["laboral_condition"].replace(0, pd.np.nan, inplace=True)
df["mun_id_trab"].replace(0, pd.np.nan, inplace=True)
df["time_to_ed_facilities"].replace(0, pd.np.nan, inplace=True)
df["transport_mean_ed_facilities"].replace(0, pd.np.nan, inplace=True)

In [59]:
df["time_to_work"] = df["time_to_work"].astype(object)
df["transport_mean_work"] = df["transport_mean_work"].astype(object)
df["academic_degree"] = df["academic_degree"].astype(object)
df["laboral_condition"] = df["laboral_condition"].astype(object)
df["mun_id_trab"] = df["mun_id_trab"].astype(object)

In [61]:
df["population"].sum()

1178800

In [30]:
df.mun_id_trab.unique()

array([nan, 1001.0, 1005.0, 1002.0, 1003.0, 1004.0, 1006.0, 1007.0,
       1009.0, 1011.0, 1010.0, 1999.0, 32007.0, 14116.0, 14999.0, 15999.0,
       32056.0, 32999.0, 14046.0, 32024.0, 32036.0, 14053.0, 1008.0,
       9999.0, 11020.0, 14035.0, 19039.0, 19999.0, 22999.0, 30999.0,
       22014.0, 24028.0, 14098.0, 15106.0, 28035.0, 9010.0, 14039.0,
       14109.0, 32025.0, 5999.0, 4002.0, 4009.0, 11015.0, 11999.0,
       21999.0, 26003.0, 15060.0, 14093.0, 14057.0, 14064.0, 32008.0,
       32052.0, 11017.0, 30072.0, 32054.0, 32020.0, 32010.0, 14073.0,
       24999.0, 18999.0, 32023.0, 32016.0, 30193.0, 15057.0, 26999.0,
       5035.0, 9003.0, 14006.0, 29033.0, 16999.0, 32019.0, 23999.0,
       15104.0, 11007.0, 27004.0, 32017.0, 14124.0, 17007.0, 8999.0,
       10999.0, 32014.0, 13048.0, 32026.0, 32044.0, 9015.0, 20067.0,
       14008.0, 21114.0, 14091.0, 32057.0, 2004.0, 12999.0, 32053.0,
       23005.0, 14080.0], dtype=object)

In [31]:
df.mun_id_trab

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
5         NaN
6         NaN
7        1001
8        1001
9        1001
10       1001
11       1001
12       1001
13       1001
14       1001
15       1001
16        NaN
17        NaN
18        NaN
19        NaN
20        NaN
21        NaN
22        NaN
23        NaN
24        NaN
25       1001
26       1001
27       1001
28       1001
29       1001
         ... 
23592     NaN
23593     NaN
23594     NaN
23595     NaN
23596     NaN
23597     NaN
23598     NaN
23599     NaN
23600     NaN
23601     NaN
23602     NaN
23603    1011
23604     NaN
23605    1002
23606     NaN
23607     NaN
23608     NaN
23609     NaN
23610     NaN
23611    1001
23612     NaN
23613    1001
23614     NaN
23615     NaN
23616     NaN
23617    1001
23618    1001
23619    1001
23620     NaN
23621     NaN
Name: mun_id_trab, Length: 23622, dtype: object

In [32]:
#df["nivacad"].replace("temp", pd.np.nan, inplace=True)
#df["mun_id_trab"].replace("temp", pd.np.nan, inplace=True)

In [33]:
df.mun_id_trab

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
5         NaN
6         NaN
7        1001
8        1001
9        1001
10       1001
11       1001
12       1001
13       1001
14       1001
15       1001
16        NaN
17        NaN
18        NaN
19        NaN
20        NaN
21        NaN
22        NaN
23        NaN
24        NaN
25       1001
26       1001
27       1001
28       1001
29       1001
         ... 
23592     NaN
23593     NaN
23594     NaN
23595     NaN
23596     NaN
23597     NaN
23598     NaN
23599     NaN
23600     NaN
23601     NaN
23602     NaN
23603    1011
23604     NaN
23605    1002
23606     NaN
23607     NaN
23608     NaN
23609     NaN
23610     NaN
23611    1001
23612     NaN
23613    1001
23614     NaN
23615     NaN
23616     NaN
23617    1001
23618    1001
23619    1001
23620     NaN
23621     NaN
Name: mun_id_trab, Length: 23622, dtype: object

In [34]:
#df["mun_id_trab"] = df["mun_id_trab"].astype(object)

In [35]:
#df.mun_id_trab.unique()

In [49]:
df.academic_degree.unique()

array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0,
       99.0, nan], dtype=object)

In [36]:
#df.age.unique()

In [37]:
df.head()

sex  parent  sersalud  dhsersal1 academic_degree laboral_condition  \
0    1       1         1          1               0                     
1    1       1         1          1               0                     
2    1       1         1          1               0                     
3    1       1         1          1               0                     
4    1       1         1          1               0                     

  time_to_work transport_mean_work    loc_id  year mun_id_trab  age  \
0                                   10010000  2010         NaN    9   
1                                   10010000  2010         NaN   13   
2                                   10010000  2010         NaN   14   
3                                   10010000  2010         NaN   15   
4                                   10010000  2010         NaN   16   

   population  
0          30  
1          17  
2          39  
3          52  
4          17

In [38]:
#df.mun_id_trab.unique()

In [39]:
len(df.columns)

13

In [40]:
df["age"].replace(999, "Edad no especificada", inplace=True)

In [41]:
df.age.unique()

array([9, 13, 14, 15, 16, 18, 19, 7, 8, 10, 12, 17, 11, 6, 4, 5, 20, 3,
       'Edad no especificada', 21, 1, 2, 23], dtype=object)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23622 entries, 0 to 23621
Data columns (total 13 columns):
sex                    23622 non-null int64
parent                 23622 non-null int64
sersalud               23622 non-null int64
dhsersal1              23622 non-null int64
academic_degree        23101 non-null object
laboral_condition      23622 non-null object
time_to_work           23622 non-null object
transport_mean_work    23622 non-null object
loc_id                 23622 non-null int64
year                   23622 non-null int64
mun_id_trab            11651 non-null object
age                    23622 non-null object
population             23622 non-null int32
dtypes: int32(1), int64(6), object(6)
memory usage: 3.1+ MB


In [43]:
""""for ele in df.edad.unique():
    try:
        df.edad = df.edad.replace(ele, int(ele))
    except:
        continue """

'"for ele in df.edad.unique():\n    try:\n        df.edad = df.edad.replace(ele, int(ele))\n    except:\n        continue '

In [44]:
# dbf = Dbf5("Migrantes_14.dbf", codec="latin-1")
# df_mig = dbf.to_dataframe()

In [45]:
# df_mig.head()


In [46]:
# df_denue = pd.read_csv('denue_inegi_31-33_.csv')
# encoding='latin-1', dtype='str', sep='\t', header=None

In [47]:
#dbf = Dbf5("DUMMY_PERSONAS.dbf", codec="latin-1")
#dummy= dbf.to_dataframe()

In [48]:
#loc_df = pd.read_csv('RESLOC_NALTXT10.txt', encoding='latin-1', dtype='str', sep='\t', header=None)